#!/usr/bin/env node
// build-viz.mjs — Node 22 ESM
// Reads data/graph.json (fallback: data/graph.stub.json), writes viz/graph-data.js
import { readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, "..");

const primary = join(root, "data", "graph.json");
const fallback = join(root, "data", "graph.stub.json");
const outDir = join(root, "viz");
const outFile = join(outDir, "graph-data.js");

let src;
if (existsSync(primary)) {
  src = primary;
  console.log("Using data/graph.json");
} else {
  src = fallback;
  console.log("data/graph.json not found — using data/graph.stub.json (stub mode)");
}

const raw = await readFile(src, "utf-8");
const graph = JSON.parse(raw);

// Basic validation
if (!graph.nodes || !graph.edges || !graph.meta) {
  throw new Error("graph JSON missing required fields: nodes, edges, meta");
}
console.log(`Loaded ${graph.nodes.length} nodes, ${graph.edges.length} edges`);

await mkdir(outDir, { recursive: true });

const js = `// AUTO-GENERATED by scripts/build-viz.mjs — do not edit manually
window.GRAPH_DATA = ${JSON.stringify(graph, null, 0)};
`;

await writeFile(outFile, js, "utf-8");
console.log(`Wrote viz/graph-data.js (${(Buffer.byteLength(js) / 1024).toFixed(1)} KB)`);
